---
version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    open-pull-requests-limit: 1
    pull-request-branch-name:
      separator: "-"
    schedule: # defined by pipeline in Hub repo, but a required property for a dependabot config
      interval: weekly
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Packages pinned due to Angular peer dependency restrictions
      - dependency-name: "typescript"
        versions: [">=5.5"]
      - dependency-name: "zone.js"
        versions: [">=0.15"]
    groups:
      all-frontend-dependencies:
        patterns:
          - "*"
