trigger: none

pool:
  name: SaaS-dev

jobs:
  - job: CI
    displayName: "CI checks"
    workspace:
      clean: all
    steps:
      - bash: docker login acrzvoovesaasdev.azurecr.io --username "$(ACR Pull Client Id)" --password "$(ACR Pull Client Secret)"
        displayName: acr login

      - bash: |
          docker build . --target=test-components -t zvoove-angular-components:test-comp
          docker build . --target=test-schematics -t zvoove-angular-components:test-schem
          docker build . --target=linter -t zvoove-angular-components:lint
        displayName: build ci images

      - bash: docker run --rm zvoove-angular-components:lint
        displayName: run linter

      - bash: docker run --rm zvoove-angular-components:test-comp
        displayName: test components

      - bash: docker run --rm zvoove-angular-components:test-schem
        displayName: test schematics

      - bash: docker rmi $(docker images --format '{{.Repository}}:{{.Tag}}' | grep 'zvoove-angular-components')
        condition: always()
        displayName: cleanup images
