---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "components"
  labels:
{{ include "default-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "components"
  template:
    metadata:
      labels:
{{ include "default-labels" . | indent 8 }}
    spec:
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: components
          image: "acrzvoovesaas{{ .Values.environment }}.azurecr.io/components:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "150Mi"
              cpu: "1m"
            limits:
              memory: "200Mi"
              cpu: "50m"
          securityContext:
            runAsUser: 1000
            capabilities:
              drop: ["ALL"]
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault"
          ports:
            - name: http-internal
              containerPort: 8080
