apiVersion: v1
kind: Service
metadata:
  name: "components"
  labels:
{{ include "default-labels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http-internal
  selector:
    app.kubernetes.io/name: "components"
