name: deploy demo
on:
  push:
    branches:
      - master

env:
  AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build . --target=test-components -t zvoove-angular-components:test-comp
          docker run --rm zvoove-angular-components:test-comp
        name: component tests

      - run: |
          docker build . --target=test-schematics -t zvoove-angular-components:test-schem
          docker run --rm zvoove-angular-components:test-schem
        name: run schematic tests

      - run: |
          docker build . --target=linter -t zvoove-angular-components:lint
          docker run --rm zvoove-angular-components:lint
        name: run linter

      - run: >
          docker build --pull . 
            -t acrzvoovesaasdev.azurecr.io/components:$(cat projects/components/package.json | jq -r '.version') 
            -t acrzvoovesaasdev.azurecr.io/components:latest
        name: build demo

      - run: |
          docker login acrzvoovesaasdev.azurecr.io --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET
          docker push acrzvoovesaasdev.azurecr.io/components:$(cat projects/components/package.json | jq -r '.version')
          docker push acrzvoovesaasdev.azurecr.io/components:latest
        name: push demo image to acr

      - run: >
          helm package ./k8s/chart/
            --app-version $(cat projects/components/package.json | jq -r '.version')
            --version $(cat projects/components/package.json | jq -r '.version')
        name: package helm chart

      - run: |
          az login --service-principal -u AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
          $env:HELM_EXPERIMENTAL_OCI=1
          az acr login -n "acrzvoovesaasdev" --expose-token --output tsv --query accessToken |
            helm registry login "acrzvoovesaasdev.azurecr.io" --username "00000000-0000-0000-0000-000000000000" --password-stdin
        name: login azure + arc

      - run: |
          helm push "components-$(cat projects/components/package.json | jq -r '.version').tgz" "oci://acrzvoovesaasdev.azurecr.io/helm"
          echo Pushed Chart Version $(cat projects/components/package.json | jq -r '.version')
        name: push helm chart
